# Generated by Django 5.1.2 on 2024-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='product',
            field=models.ManyToManyField(blank=True, to='retail.product', verbose_name='Продукт'),
        ),
    ]
