# Generated by Django 5.1.2 on 2024-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_network_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], default=0, verbose_name='Уровень иерархии'),
        ),
    ]
